# Generated by Django 6.0.1 on 2026-02-16 17:23

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(blank=True, null=True, verbose_name='Imagen URL')),
                ('titulo', models.CharField(max_length=300, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('profesional', models.CharField(blank=True, max_length=200, verbose_name='Profesional')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
                'ordering': ['-creado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='Logo URL')),
                ('resumen', models.TextField(blank=True, verbose_name='Resumen')),
                ('ruta', models.SlugField(max_length=150, unique=True, verbose_name='Ruta')),
                ('titulo', models.CharField(blank=True, max_length=300, verbose_name='Titulo')),
                ('banner', models.URLField(blank=True, null=True, verbose_name='Banner URL')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('catalogo_pdf', models.URLField(blank=True, null=True, verbose_name='Catalogo PDF URL')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
                'db_table': 'portafolios',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Promocion')),
                ('banner', models.URLField(blank=True, null=True, verbose_name='Banner URL')),
                ('titulo', models.CharField(max_length=300, verbose_name='Titulo')),
                ('subtitulo', models.CharField(blank=True, max_length=100, verbose_name='Subtitulo')),
                ('descripcion', models.TextField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('texto_boton', models.CharField(blank=True, max_length=100, verbose_name='Texto del Botón')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promociones',
                'ordering': ['creado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Ultimo ingreso')),
                ('role', models.CharField(choices=[('general', 'General'), ('profesional', 'Profesional')], default='general', max_length=30, verbose_name='Role')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso al panel')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super usuario')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Accion')),
                ('tipo_objeto', models.CharField(blank=True, max_length=100, verbose_name='Tipo objeto')),
                ('id_objeto', models.IntegerField(blank=True, null=True, verbose_name='ID objeto')),
                ('datos', models.JSONField(blank=True, null=True, verbose_name='Datos')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_cambios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoria Cambio',
                'verbose_name_plural': 'Auditoria Cambios',
                'db_table': 'auditoria_cambios',
                'ordering': ['-creado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.JSONField(verbose_name='Productos')),
                ('total', models.BigIntegerField(verbose_name='Total (COP)')),
                ('numero_whatsapp', models.CharField(blank=True, max_length=30, verbose_name='Numero de WhatsApp')),
                ('mensaje_whatsapp', models.TextField(blank=True, verbose_name='Mensaje de WhatsApp')),
                ('metadatos_cliente', models.JSONField(blank=True, null=True, verbose_name='Metadatos del cliente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_compras', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Historial Compra',
                'verbose_name_plural': 'Historial Compras',
                'db_table': 'historial_compras',
                'ordering': ['-creado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=api.models.default_expiration)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(blank=True, null=True, verbose_name='Imagen URL')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('precio', models.BigIntegerField(verbose_name='Precio (COP)')),
                ('descuento', models.IntegerField(blank=True, null=True, verbose_name='% Descuento')),
                ('precio_descuento', models.BigIntegerField(blank=True, null=True, verbose_name='Precio con descuento (COP)')),
                ('tipo_usuario', models.CharField(choices=[('general', 'General'), ('profesional', 'Profesional')], default='general', max_length=30, verbose_name='Tipo de usuario')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio', to='api.portafolio', verbose_name='Portafolio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
    ]
