# Generated by Django 6.0.1 on 2026-04-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_producto_portafolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='portafolios/banners/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='catalogo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='portafolios/catalogos/', verbose_name='Catalogo PDF'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='portafolios/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/banners/', verbose_name='Banner'),
        ),
    ]
