# Generated by Django 6.0.1 on 2026-05-21 23:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_curso_img_alter_portafolio_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.portafolio_banner_upload_to, verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='catalogo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=api.models.portafolio_catalogo_upload_to, verbose_name='Catalogo PDF'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='descripcion',
            field=models.TextField(blank=True, max_length=700, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.portafolio_logo_upload_to, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='resumen',
            field=models.TextField(blank=True, max_length=80, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='ruta',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titulo'),
        ),
    ]
