# Generated by Django 6.0.1 on 2026-05-22 00:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_portafolio_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.curso_img_upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesional',
            field=models.CharField(blank=True, max_length=50, verbose_name='Profesional'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.producto_img_upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.promocion_img_upload_to, verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Promocion'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='texto_boton',
            field=models.CharField(blank=True, max_length=30, verbose_name='Texto del Botón'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
