# Generated by Django 6.0.1 on 2026-05-24 02:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_curso_descripcion_alter_curso_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='banner',
            field=models.ImageField(default='sin valor', upload_to=api.models.portafolio_banner_upload_to, verbose_name='Banner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='descripcion',
            field=models.TextField(max_length=700, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='logo',
            field=models.ImageField(default='', upload_to=api.models.portafolio_logo_upload_to, verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='resumen',
            field=models.TextField(max_length=80, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descripción'),
        ),
    ]
