# Generated by Django 6.0.1 on 2026-05-25 17:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_portafolio_banner_alter_portafolio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='img',
            field=models.ImageField(default='', upload_to=api.models.curso_img_upload_to, verbose_name='Imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='link',
            field=models.URLField(max_length=600, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesional',
            field=models.CharField(max_length=50, verbose_name='Profesional'),
        ),
    ]
