# Generated by Django 6.0.1 on 2026-05-25 17:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_curso_descripcion_alter_curso_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=300, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(default='', upload_to=api.models.producto_img_upload_to, verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
