# Generated by Django 6.0.1 on 2026-05-29 15:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_producto_descripcion_alter_producto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='banner',
            field=models.ImageField(default='', upload_to=api.models.promocion_img_upload_to, verbose_name='Banner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='link',
            field=models.CharField(max_length=600, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='subtitulo',
            field=models.CharField(max_length=50, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='texto_boton',
            field=models.CharField(max_length=30, verbose_name='Texto del Botón'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
